site_name: PinteYa! Documentación
site_url: https://santiagomartinezmm.github.io/pinteya-ecommerce
repo_url: https://github.com/SantiagoMartinezMm/pinteya-ecommerce
repo_name: SantiagoMartinezMm/pinteya-ecommerce

theme:
  name: material
  language: es
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Inicio: index.md
  - Guías:
      - Instalación: guides/installation.md
      - Desarrollo: guides/development.md
      - Despliegue: guides/deployment.md
  - API:
      - Introducción: api/introduction.md
      - Autenticación: api/authentication.md
      - Endpoints: api/endpoints.md
  - Arquitectura:
      - Visión General: architecture/overview.md
      - Frontend: architecture/frontend.md
      - Backend: architecture/backend.md
      - Base de Datos: architecture/database.md
  - Contribución:
      - Guía: contributing/guide.md
      - Código de Conducta: contributing/code-of-conduct.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html

plugins:
  - search
  - git-revision-date-localized:
      type: datetime
      locale: es
  - minify:
      minify_html: true
